---
# yaml-language-server: $schema=https://schema.blue-build.org/module-list-v1.json

modules:
 - type: files
   files:
     - source: system
       destination: /

 - type: dnf
   install:
     install-weak-deps: false
     packages:
      - kernel-tools-libs
      - kernel-modules-extra
      - alsa-ucm
      - alsa-utils
      - libcamera-ipa
      - libinput
      - systemd-oomd-defaults
      - uresourced
      - libinput-utils
      - lm_sensors
      - usbutils
      - pciutils
      - v4l-utils
      - dbus-daemon
      - unbound-anchor
      - usbmuxd
      - flatpak
      - zram-generator
      - zram-generator-defaults

 - type: kargs
   kargs:
      - loglevel=3
      - rd.udev.log_level=3
      - nowatchdog
      - mitigations=auto
      - sched_autogroup_enabled=0
      - i915.enable_psr=0
      - split_lock_detect=off
      - split_lock_mitigate=0
      - transparent_hugepage=always
      - zswap.enabled=0

 - type: script
   scripts:
       - setup-usr-executables.sh
