---
# yaml-language-server: $schema=https://schema.blue-build.org/module-list-v1.json

modules:
 - type: dnf
   install:
     install-weak-deps: false
     packages:
    # => Alsa Core
      - alsa-ucm
      - alsa-sof-firmware
      - alsa-firmware
      - alsa-tools-firmware
    # => LibCamera
      - libcamera
      - libcamera-ipa
      - libcamera-gstreamer
      - libcamera-v4l2
      - pipewire-plugin-libcamera
    # => V4l & libGP
      - gphoto2
      - libgphoto2
      - pipewire-v4l2
    # => Kernel Modules
      - linux-firmware
      - kernel-tools-libs
      - kernel-modules-extra
    # => Init & Defaults
      - systemd-oomd-defaults
      - uresourced
      - inotify-tools
      - dbus-daemon
      - unbound-anchor
      - zram-generator
      - vulkan-tools
      - usb_modeswitch
    # => User Apps
      - flatpak
    # => Nix
      - nix
      - nix-daemon
      - busybox
      - glibc
      - sqlite
      - patch
      - make
    # => System stats
      - mangohud
    # => TPM2.0 Support
      - tpm2-tools
    # => fuse (Appimage & winboat)
      - fuse
      - fuse-libs
      - freerdp
    #=> Zsh Shell
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    #=> Plymouth
      - plymouth
      - plymouth-plugin-two-step