---
# yaml-language-server: $schema=https://schema.blue-build.org/module-list-v1.json

modules:
 - type: dnf
   install:
     install-weak-deps: false
     packages:
    # => Alsa Core
      - alsa-ucm
      - alsa-sof-firmware
      - alsa-firmware
      - alsa-tools-firmware
    # => Kernel Modules
      - linux-firmware
      - kernel-tools-libs
      - kernel-modules-extra
    # => Init & Defaults
      - systemd-oomd-defaults
      - uresourced
      - dbus-daemon
      - unbound-anchor
      - zram-generator
      - vulkan-tools
      - usb_modeswitch
    # => User Apps
      - flatpak
      - mangohud
    # => TPM2.0 Support
      - tpm2-tools
    # => fuse (Appimage & winboat)
      - fuse
      - fuse-libs
      - freerdp
    #=> Zsh Shell
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    #=> Plymouth
      - plymouth
      - plymouth-plugin-two-step